import { supabase } from '../lib/supabase';

export const samplePlaces = [
  {
    name: 'Sky Zone Trampoline Park - South Plainfield',
    overview: 'Large indoor trampoline park with a dedicated Toddler Zone, open jump courts, foam pits, Air Court, and party rooms. Good option for a 5-year-old if you go during off-peak hours.',
    address: '600 Hadley Rd, South Plainfield, NJ 07080',
    google_maps_url: 'https://www.google.com/maps/place/Sky+Zone+Trampoline+Park,+600+Hadley+Rd,+South+Plainfield,+NJ+07080',
    distance_miles: 9.5,
    drive_time_minutes: 22,
    category: 'Indoor Attraction',
    subcategory: 'Trampoline Park',
    key_highlights: 'Toddler Zone designed for younger kids; Freestyle Jump; Foam Zone; Air Court; Family Slide/SkyHoops; birthday party packages',
    insider_tips: 'Go at opening on Tue–Thu to avoid big-kid crowds; skip GLOW for noise/sensory-sensitive kids. Pre-sign the online waiver and book a start time; arrive 20 minutes early to get wristbands and socks.',
    entry_fee: 'Varies by session; book online. Typical range: 60 min ≈ $25–$30 per jumper',
    average_spend: 55,
    best_seasons: 'Year-round; ideal for winter, rainy days, and very hot days',
    best_day: 'Tuesday–Thursday mornings (least crowded)',
    parking_info: 'Free on-site lot (shared plaza); busiest on weekends',
    ev_charging: 'No dedicated chargers on-site; public stations available nearby',
    google_rating: 3.8,
    tripadvisor_rating: 3.7,
    overall_sentiment: 'Mixed-positive: kids love it and staff are often friendly; best experiences reported during off-peak times.',
    nearby_restaurants: [
      { name: 'Panera Bread', description: 'Soups/sandwiches, kid-friendly', distance: '~0.3 mi' },
      { name: 'Chipotle Mexican Grill', description: 'Customizable bowls/tacos; kid meals', distance: '~0.3 mi' },
      { name: 'Chick-fil-A', description: 'Chicken sandwiches/nuggets; kids\' meals', distance: '~1.0 mi' }
    ],
    average_visit_duration: '1.5–2 hours',
    upcoming_events: 'GLOW (blacklight) nights on select weekends; Little Leapers toddler sessions',
    visited: false
  },
  {
    name: 'Turtle Back Zoo',
    overview: 'Turtle Back Zoo, located in West Orange, New Jersey, is a family-friendly destination featuring over 100 species of animals, including giraffes, penguins, and bears. It offers interactive experiences like a miniature train ride, a petting zoo, and a treetop adventure course.',
    address: '560 Northfield Ave, West Orange, NJ 07052',
    google_maps_url: 'https://www.google.com/maps/place/Turtle+Back+Zoo/@40.7678,-74.2855,17z',
    distance_miles: 25,
    drive_time_minutes: 35,
    category: 'Outdoor Attraction',
    subcategory: 'Zoo',
    key_highlights: 'Diverse animal exhibits, interactive experiences like the petting zoo and train ride, seasonal events such as Boo at the Zoo, playground areas for kids',
    insider_tips: 'Arrive early to beat the crowds and secure parking close to the entrance; bring a stroller for a 5-year-old as the zoo involves a lot of walking; check the feeding schedules online to plan your visit around interactive animal experiences',
    entry_fee: 'Adults (13-61): $17, Children (2-12): $14, Seniors (62+): $14, Free for children under 2',
    average_spend: 60,
    best_seasons: 'Spring and Fall for pleasant weather and fewer crowds',
    best_day: 'Wednesday for lower attendance and a calmer experience',
    parking_info: 'Ample parking available at South Mountain Recreation Complex, $10 fee on weekends and holidays, free on weekdays',
    ev_charging: 'Limited EV charging stations available at South Mountain Recreation Complex parking area',
    google_rating: 4.5,
    tripadvisor_rating: 4.0,
    overall_sentiment: 'Highly positive; families praise the variety of animals, cleanliness, and kid-friendly activities, though some note crowded weekends',
    nearby_restaurants: [
      { name: 'The Juke Joint Soul Kitchen', description: 'Family-friendly Southern comfort food', distance: '10-minute drive' },
      { name: 'Tito\'s Burritos & Wings', description: 'Casual Mexican eatery, kid-friendly menu', distance: '15-minute drive' },
      { name: 'Whole Foods Market Cafe', description: 'Healthy grab-and-go options for families', distance: '5-minute drive' }
    ],
    average_visit_duration: '3-4 hours',
    upcoming_events: 'Boo at the Zoo (October 2025), Holiday Lights Spectacular (November-December 2025)',
    visited: false
  },
  {
    name: 'Liberty Science Center',
    overview: 'Liberty Science Center is a premier interactive science museum and learning center located in Jersey City, New Jersey. It features hundreds of hands-on exhibits, live demonstrations, the largest planetarium in the Western Hemisphere, and dedicated play zones for younger visitors.',
    address: '222 Jersey City Blvd, Jersey City, NJ 07305',
    google_maps_url: 'https://www.google.com/maps/place/Liberty+Science+Center',
    distance_miles: 37,
    drive_time_minutes: 50,
    category: 'Museum',
    subcategory: 'Science Center',
    key_highlights: 'Jennifer Chalsty Planetarium (largest in the Western Hemisphere), Wobbly World and I Explore zones for younger children, Touch Tunnel crawl experience, Dino Dig, live animal exhibits',
    insider_tips: 'Arrive early to beat school groups and secure timed tickets for the Planetarium. Bring snacks or eat before entering—the on-site cafeteria is convenient but pricey. Buying parking online with admission saves time.',
    entry_fee: 'Approximately $30 per adult, $25 per child (ages 2–12); separate fee for special exhibits or planetarium shows',
    average_spend: 150,
    best_seasons: 'Year-round (indoor attraction). Fall and winter are best for fewer crowds',
    best_day: 'Wednesday or Thursday morning for minimal wait times',
    parking_info: 'On-site paid parking lot ($7–$10/day); buy online to save $2',
    ev_charging: 'Limited EV charging stations available in the main parking lot',
    google_rating: 4.5,
    tripadvisor_rating: 4.0,
    overall_sentiment: 'Highly positive – families love the hands-on exhibits and educational value. A few reviews mention it gets noisy and crowded, but staff handle crowd flow well',
    nearby_restaurants: [
      { name: 'Liberty House Restaurant', description: 'Upscale but family-friendly dining with views of the Manhattan skyline' },
      { name: 'Brownstone Diner & Pancake Factory', description: 'Casual spot known for excellent pancakes and breakfast all day' },
      { name: 'Café Peanut', description: 'Cozy local café serving sandwiches, wraps, frappes, and smoothies' }
    ],
    average_visit_duration: '3–5 hours',
    upcoming_events: 'Winter 2025 Planetarium series: Stars of Sesame Street live astronomy show for preschoolers (Nov–Feb)',
    visited: false
  },
  {
    name: 'Adventure Aquarium',
    overview: 'One of the premier aquariums in the US, featuring hippos, sharks, penguins, and interactive touch tanks. Located on the Camden waterfront with views of Philadelphia.',
    address: '1 Riverside Dr, Camden, NJ 08103',
    google_maps_url: 'https://www.google.com/maps/place/Adventure+Aquarium',
    distance_miles: 62,
    drive_time_minutes: 75,
    category: 'Museum',
    subcategory: 'Aquarium',
    key_highlights: 'Hippo Haven, Shark Bridge walkway, penguin island, stingray touch tank, 4D theater experiences',
    insider_tips: 'Purchase tickets online to save money and skip the box office line. Visit on weekday mornings for smaller crowds. The shark tunnel is best experienced early before crowds arrive.',
    entry_fee: 'Adults: $35, Children (2-12): $25, under 2 free',
    average_spend: 120,
    best_seasons: 'Year-round indoor attraction; summer offers waterfront activities nearby',
    best_day: 'Tuesday or Wednesday mornings',
    parking_info: 'Paid parking garage adjacent to aquarium ($15-20)',
    ev_charging: 'EV charging available at nearby parking facilities',
    google_rating: 4.4,
    tripadvisor_rating: 4.0,
    overall_sentiment: 'Very positive; visitors love the diverse exhibits and interactive experiences, particularly the hippos and shark tunnel',
    nearby_restaurants: [
      { name: 'Chickie\'s & Pete\'s', description: 'Family sports bar famous for crabfries', distance: 'Adjacent' },
      { name: 'Iron Hill Brewery', description: 'Craft brewery with full menu', distance: '0.2 mi' }
    ],
    average_visit_duration: '3-4 hours',
    upcoming_events: 'Penguin Encounter experiences, Dive with Sharks programs',
    visited: false
  },
  {
    name: 'Grounds For Sculpture',
    overview: '42-acre sculpture park and museum featuring contemporary sculptures set in beautifully landscaped gardens. Indoor galleries and outdoor installations throughout.',
    address: '80 Sculptors Way, Hamilton, NJ 08619',
    google_maps_url: 'https://www.google.com/maps/place/Grounds+For+Sculpture',
    distance_miles: 45,
    drive_time_minutes: 55,
    category: 'Outdoor Attraction',
    subcategory: 'Sculpture Park',
    key_highlights: '270+ sculptures by renowned and emerging artists, themed gardens, climate-controlled pavilions, family-friendly scavenger hunts',
    insider_tips: 'Wear comfortable walking shoes. Pick up a family guide at entrance for kid-friendly sculpture descriptions. The Peacock Café requires reservations on weekends.',
    entry_fee: 'Adults: $20, Children (under 10): Free, Students/Seniors: $18',
    average_spend: 75,
    best_seasons: 'Spring (blooming gardens) and Fall (autumn colors)',
    best_day: 'Friday for quieter experience',
    parking_info: 'Free on-site parking lot',
    ev_charging: 'No dedicated EV charging currently',
    google_rating: 4.6,
    tripadvisor_rating: 4.5,
    overall_sentiment: 'Excellent; visitors praise the beautiful setting, diverse artwork, and peaceful atmosphere',
    nearby_restaurants: [
      { name: 'Rats Restaurant', description: 'Fine dining on-site inspired by Monet\'s Giverny' },
      { name: 'Van Gogh\'s Ear Café', description: 'Casual café on-site with sandwiches and pastries' }
    ],
    average_visit_duration: '2-3 hours',
    upcoming_events: 'Summer Concert Series, Holiday Light Show (December)',
    visited: false
  },
  {
    name: 'Diggerland USA',
    overview: 'Unique construction-themed adventure park where kids and adults can operate real heavy machinery. Features diggers, dump trucks, and construction-themed rides.',
    address: '100 Pinedge Dr, West Berlin, NJ 08091',
    google_maps_url: 'https://www.google.com/maps/place/Diggerland+USA',
    distance_miles: 68,
    drive_time_minutes: 80,
    category: 'Theme Park',
    subcategory: 'Construction Adventure Park',
    key_highlights: 'Operate real excavators, ride in dump trucks, Spin Dizzy ride, Groundshuttle roller coaster, water park included in summer',
    insider_tips: 'Height requirements vary by attraction (36"-42" minimum for most). Book online for discounts. Arrive at opening for shortest lines. Bring bathing suits in summer for water features.',
    entry_fee: '$36-45 per person depending on season; under 3 free',
    average_spend: 120,
    best_seasons: 'Spring through Fall; water park open Memorial Day to Labor Day',
    best_day: 'Weekdays in May or September for minimal crowds',
    parking_info: 'Free parking on-site',
    ev_charging: 'No EV charging available',
    google_rating: 4.3,
    tripadvisor_rating: 4.0,
    overall_sentiment: 'Very positive; kids love operating real machinery, though some parents note it can feel small for the price',
    nearby_restaurants: [
      { name: 'On-site snack bar', description: 'Basic food options available' },
      { name: 'Red Robin', description: 'Family burgers and shakes', distance: '5 minutes' }
    ],
    average_visit_duration: '3-5 hours',
    upcoming_events: 'Trucks & Treats Halloween event (October)',
    visited: false
  },
  {
    name: 'Jenkinson\'s Boardwalk',
    overview: 'Classic Jersey Shore boardwalk with amusement rides, arcade, aquarium, mini golf, and beach access. Family-friendly entertainment destination.',
    address: '300 Ocean Ave, Point Pleasant Beach, NJ 08742',
    google_maps_url: 'https://www.google.com/maps/place/Jenkinsons+Boardwalk',
    distance_miles: 52,
    drive_time_minutes: 70,
    category: 'Outdoor Attraction',
    subcategory: 'Boardwalk & Beach',
    key_highlights: 'Kiddie rides and games, Jenkinson\'s Aquarium, mini golf, beach access, arcades, sweet shops',
    insider_tips: 'Buy ride tickets in bulk for savings. Aquarium is great for hot/rainy days. Beach tags required in season. Go early morning or after 5pm to avoid peak crowds.',
    entry_fee: 'Free boardwalk access; rides require tickets ($1.50-2.50 each), Aquarium: $15 adults/$12 kids',
    average_spend: 100,
    best_seasons: 'Late Spring through Early Fall for full operations',
    best_day: 'Tuesday or Wednesday for fewer crowds',
    parking_info: 'Paid metered parking and lots ($2-3/hour, $15-25/day in season)',
    ev_charging: 'Municipal charging stations within 2 blocks',
    google_rating: 4.4,
    tripadvisor_rating: 4.0,
    overall_sentiment: 'Positive; families appreciate the nostalgic boardwalk feel and variety of activities',
    nearby_restaurants: [
      { name: 'Martell\'s Tiki Bar', description: 'Waterfront dining with kid menu' },
      { name: 'Jenkinson\'s Pavilion', description: 'On-site casual dining' },
      { name: 'Hoffman\'s Ice Cream', description: 'Classic ice cream parlor' }
    ],
    average_visit_duration: '4-6 hours',
    upcoming_events: 'Summer concerts, fireworks displays (July-August)',
    visited: false
  },
  {
    name: 'Cape May County Park & Zoo',
    overview: 'Free admission zoo in a beautiful park setting with over 550 animals representing 250 species. One of the best free zoos in the country.',
    address: '707 US-9, Cape May Court House, NJ 08210',
    google_maps_url: 'https://www.google.com/maps/place/Cape+May+County+Park+and+Zoo',
    distance_miles: 115,
    drive_time_minutes: 135,
    category: 'Outdoor Attraction',
    subcategory: 'Zoo',
    key_highlights: 'Free admission, African savanna exhibit, World of Birds aviary, reptile house, playground, walking trails',
    insider_tips: 'Completely free but donations appreciated. Bring your own food for picnic areas. Visit in morning when animals are most active. Wear comfortable shoes for walking.',
    entry_fee: 'FREE (donations accepted)',
    average_spend: 30,
    best_seasons: 'Spring and Fall for comfortable temperatures',
    best_day: 'Weekdays for quieter experience',
    parking_info: 'Free parking lots throughout the park',
    ev_charging: 'No dedicated EV charging',
    google_rating: 4.7,
    tripadvisor_rating: 4.5,
    overall_sentiment: 'Excellent; visitors rave about the quality and variety for a free zoo',
    nearby_restaurants: [
      { name: 'Zoo Café', description: 'On-site café with basic meals' },
      { name: 'Pic-A-Lilli Inn Restaurant', description: 'Family dining nearby', distance: '5 minutes' }
    ],
    average_visit_duration: '2-3 hours',
    upcoming_events: 'Boo at the Zoo (October), Wild Lights holiday display (November-December)',
    visited: false
  },
  {
    name: 'Crayola Experience',
    overview: 'Interactive attraction featuring 25+ hands-on activities all about creativity and color. Kids can name and wrap their own crayon, create art projects, and play in colorful environments.',
    address: '30 Centre Square, Easton, PA 18042',
    google_maps_url: 'https://www.google.com/maps/place/Crayola+Experience',
    distance_miles: 58,
    drive_time_minutes: 70,
    category: 'Indoor Attraction',
    subcategory: 'Interactive Arts Center',
    key_highlights: 'Name your own crayon, melted wax hands, drip art, wrap designer, digital design stations, toddler town play area',
    insider_tips: 'Purchase tickets online for discount. Visit on weekday mornings to avoid school groups. Wear clothes that can get messy. Allow 2-3 hours to experience all activities.',
    entry_fee: 'General admission: $27, Under 2: Free',
    average_spend: 90,
    best_seasons: 'Year-round indoor attraction',
    best_day: 'Tuesday-Thursday mornings',
    parking_info: 'Parking garage next door ($1-2/hour)',
    ev_charging: 'EV charging in adjacent parking facilities',
    google_rating: 4.5,
    tripadvisor_rating: 4.0,
    overall_sentiment: 'Very positive; families love the creative activities and kids leave with custom creations',
    nearby_restaurants: [
      { name: 'Melt', description: 'Gourmet grilled cheese restaurant', distance: 'Within Centre Square' },
      { name: 'Maxim\'s 22', description: 'Family-friendly American cuisine', distance: '2 blocks' }
    ],
    average_visit_duration: '2-3 hours',
    upcoming_events: 'Special themed events and workshops throughout the year',
    visited: false
  },
  {
    name: 'Sesame Place',
    overview: 'Theme park based on Sesame Street with rides, shows, and character meet-and-greets. Includes water park in summer months.',
    address: '100 Sesame Rd, Langhorne, PA 19047',
    google_maps_url: 'https://www.google.com/maps/place/Sesame+Place',
    distance_miles: 65,
    drive_time_minutes: 75,
    category: 'Theme Park',
    subcategory: 'Character Theme Park',
    key_highlights: 'Dry rides for all ages, water park (summer), character parades, Elmo\'s World, Cookie Mountain, live shows',
    insider_tips: 'Buy tickets online in advance for best prices. Arrive at park opening. Character meet-and-greets have shortest lines early morning. Bring bathing suits for water attractions.',
    entry_fee: '$80-100 per person (cheaper online), under 2 free',
    average_spend: 280,
    best_seasons: 'May through October; water park open June-August',
    best_day: 'Weekdays in May or September',
    parking_info: 'Paid parking $30',
    ev_charging: 'EV charging stations available in parking lot',
    google_rating: 4.3,
    tripadvisor_rating: 3.5,
    overall_sentiment: 'Mixed-positive; perfect for young Sesame Street fans, but can be expensive and crowded',
    nearby_restaurants: [
      { name: 'Multiple on-site restaurants', description: 'Pizza, burgers, chicken tenders' }
    ],
    average_visit_duration: '6-8 hours',
    upcoming_events: 'Halloween Spooktacular (September-October), Very Furry Christmas (November-December)',
    visited: false
  },
  {
    name: 'Storybook Land',
    overview: 'Charming storybook-themed amusement park designed for young children with 20+ rides and attractions based on nursery rhymes and fairy tales.',
    address: '6415 Black Horse Pike, Egg Harbor Township, NJ 08234',
    google_maps_url: 'https://www.google.com/maps/place/Storybook+Land',
    distance_miles: 98,
    drive_time_minutes: 115,
    category: 'Theme Park',
    subcategory: 'Children\'s Amusement Park',
    key_highlights: 'Child-sized rides, storybook buildings, petting zoo, Bubbles the Coaster, train ride, Christmas light display',
    insider_tips: 'Perfect for ages 2-8. Most rides accommodate parents with small children. Less crowded than major parks. Pack your own lunch to save money.',
    entry_fee: '$30-35 per person, under 1 free',
    average_spend: 100,
    best_seasons: 'Spring through Fall; Christmas lights in November-December',
    best_day: 'Weekdays for minimal wait',
    parking_info: 'Free parking on-site',
    ev_charging: 'No dedicated EV charging',
    google_rating: 4.5,
    tripadvisor_rating: 4.5,
    overall_sentiment: 'Very positive; perfect first theme park for young children, well-maintained and reasonably priced',
    nearby_restaurants: [
      { name: 'On-site concessions', description: 'Pizza, hot dogs, snacks' },
      { name: 'Shore restaurants', description: 'Many options 10-15 minutes away' }
    ],
    average_visit_duration: '3-4 hours',
    upcoming_events: 'Haunted nights (October), Christmas display (November-December)',
    visited: false
  },
  {
    name: 'Duke Farms',
    overview: 'Sprawling 2,740-acre estate with lakes, trails, orchards, and farm buildings. Focus on environmental stewardship and outdoor education.',
    address: '1112 Dukes Pkwy W, Hillsborough Township, NJ 08844',
    google_maps_url: 'https://www.google.com/maps/place/Duke+Farms',
    distance_miles: 28,
    drive_time_minutes: 38,
    category: 'Outdoor Attraction',
    subcategory: 'Nature Reserve & Park',
    key_highlights: 'Free admission, 18 miles of trails, Orientation Center with exhibits, Farm Barn, Orchid Range (seasonal), bike rentals, educational programs',
    insider_tips: 'Completely free. Bring bikes or rent on-site. Pack a picnic. Check event calendar for family programs. Orchid Range only open certain months.',
    entry_fee: 'FREE',
    average_spend: 20,
    best_seasons: 'Spring (orchids & blooms) and Fall (foliage)',
    best_day: 'Weekdays for peaceful experience',
    parking_info: 'Free parking at Orientation Center',
    ev_charging: 'EV charging stations available in parking lot',
    google_rating: 4.7,
    tripadvisor_rating: 4.5,
    overall_sentiment: 'Excellent; visitors love the free access, beautiful grounds, and family-friendly atmosphere',
    nearby_restaurants: [
      { name: 'Café at Duke Farms', description: 'On-site café with sandwiches and drinks' },
      { name: 'Picnic areas throughout', description: 'Bring your own food' }
    ],
    average_visit_duration: '2-4 hours',
    upcoming_events: 'Seasonal educational programs, nature walks, family workshops',
    visited: false
  },
  {
    name: 'Battleship New Jersey Museum & Memorial',
    overview: 'Historic battleship museum offering self-guided and guided tours of the most decorated battleship in US Navy history. Interactive exhibits and hands-on experiences.',
    address: '62 Battleship Pl, Camden, NJ 08103',
    google_maps_url: 'https://www.google.com/maps/place/Battleship+New+Jersey',
    distance_miles: 62,
    drive_time_minutes: 75,
    category: 'Museum',
    subcategory: 'Historic Naval Ship',
    key_highlights: 'Self-guided audio tours, fire power tour, Broadway show on weekends, overnight camping programs, climb into turrets',
    insider_tips: 'Buy tickets online to save. Wear comfortable shoes - lots of stairs and ladders. The Turret II tour is excellent but requires climbing. Allow 2-3 hours minimum.',
    entry_fee: 'Adults: $25, Children (5-11): $17, Under 5: Free',
    average_spend: 85,
    best_seasons: 'Spring and Fall for comfortable deck temps',
    best_day: 'Weekdays for smaller crowds',
    parking_info: 'Free parking on-site',
    ev_charging: 'EV charging nearby at waterfront facilities',
    google_rating: 4.7,
    tripadvisor_rating: 4.5,
    overall_sentiment: 'Excellent; history buffs and families love the interactive experience and well-preserved ship',
    nearby_restaurants: [
      { name: 'Camden waterfront restaurants', description: 'Multiple options nearby' },
      { name: 'Adventure Aquarium café', description: '5 minute walk' }
    ],
    average_visit_duration: '2-3 hours',
    upcoming_events: 'Overnight encampments for scouts, special military history events',
    visited: false
  }
];

export async function importSampleData() {
  try {
    const { data, error } = await supabase
      .from('places')
      .insert(samplePlaces);

    if (error) throw error;

    console.log('Successfully imported sample data:', data);
    return { success: true, count: samplePlaces.length };
  } catch (error) {
    console.error('Error importing sample data:', error);
    return { success: false, error };
  }
}
